// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXF4tewSQNh0Lm4lLdwSypx6uppjScMKk',
    appId: '1:936124374565:web:5c1d954fa9c07b6d1769cc',
    messagingSenderId: '936124374565',
    projectId: 'ideagram-d6a62',
    authDomain: 'ideagram-d6a62.firebaseapp.com',
    storageBucket: 'ideagram-d6a62.appspot.com',
    measurementId: 'G-5J1NJT46QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEEVUdC4X22aT0XUC1wJVqoTEm6KoC7Lc',
    appId: '1:936124374565:android:ccbd15d89e10d9ce1769cc',
    messagingSenderId: '936124374565',
    projectId: 'ideagram-d6a62',
    storageBucket: 'ideagram-d6a62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfQCrl64oO5JaqRsZl_TV-4Gr-P-i_v-A',
    appId: '1:936124374565:ios:aaf986a94047d02c1769cc',
    messagingSenderId: '936124374565',
    projectId: 'ideagram-d6a62',
    storageBucket: 'ideagram-d6a62.appspot.com',
    iosClientId: '936124374565-k0cf8nva8f3laoels2bgan6g0fp44tmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ideaGram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfQCrl64oO5JaqRsZl_TV-4Gr-P-i_v-A',
    appId: '1:936124374565:ios:3beca0c18c5c1c181769cc',
    messagingSenderId: '936124374565',
    projectId: 'ideagram-d6a62',
    storageBucket: 'ideagram-d6a62.appspot.com',
    iosClientId: '936124374565-bjh1uq66v6jgu1ahie3h6ogrs4u78gk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ideaGram.RunnerTests',
  );
}
